predictor: "prev_y9"
target: "eir"
name: "${predictor}-${target}"

# Data
features_scaler_file: ${output_dir}/features_scaler.pkl
target_scaler_file: ${output_dir}/target_scaler.pkl


# Model - ensure these match the checkpointed model's parameters
model_name: "RQS"
width: 256
depth: 2
mlp_residual: false
n_bins: 24
rqs_bounds: 6
dropout_rate: 0.0
conformal_file: "${output_dir}/conformal-${timestamp}.json"

# Checkpointing
checkpoint_dir: "${output_dir}/ckpts-${timestamp}"

# General
output_dir: "train_outputs/${name}"
timestamp: ???
seed: 42
artifact_dir: "artifacts/${name}"